# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_news', '0003_auto_20170423_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
