# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_news', '0006_remove_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
